from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('service/', views.service, name="service"),
    path('team/', views.team, name="team"),
    path('testimonial/', views.testimonial, name="testimonial"),
    path('contact/', views.contact, name="contact"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register_view, name="register"),
    path('register/owner/', views.register_owner_view, name="register_owner"),
    path('profile/', views.profile_view, name="profile"),
    path("car/", views.car, name="car"),
    path("car/partial/", views.car_partial, name="car_partial"),
    path('detail/<int:pk>/', views.detail, name="detail"),
    path('search/', views.search_cars, name="search_cars"),
    path('booking/', views.booking_view, name="booking"),
    path('booking/<int:booking_id>/approve/', views.approve_booking, name="approve_booking"),
    path('booking/<int:booking_id>/reject/', views.reject_booking, name="reject_booking"),
    path('owner/dashboard/', views.owner_dashboard, name="owner_dashboard"),
    path('owner/add-car/', views.add_car, name="add_car"),
    path("car/<int:car_id>/edit/", views.edit_car, name="edit_car"),
    path("car/<int:car_id>/delete/", views.delete_car, name="delete_car"),
    path('owner/<int:owner_id>/cars/', views.owner_cars, name="owner_cars"),
    path('owner/<int:owner_id>/', views.owner_profile, name="owner_profile"),
    path('companies/', views.companies_list, name="companies_list"),
    path("my-bookings/", views.my_bookings, name="my_bookings"),
    path("booking/<int:booking_id>/pay/", views.pay_booking, name="pay_booking"),
    path("payment/success/", views.payment_success, name="payment_success"),
    path("payment/cancel/", views.payment_cancel, name="payment_cancel"),
    path("owner/<int:owner_id>/bookings/", views.owner_bookings, name="owner_bookings"),
    path("super/login/", views.admin_login, name="admin_login"),
    path("dashboard/admin/", views.admin_dashboard, name="admin_dashboard"),
    path("dashboard/admin/export-excel/", views.export_admin_report_excel, name="export_excel"),
    path("dashboard/admin/export-pdf/", views.export_admin_report_pdf, name="export_pdf"),
     path("contracts/<int:booking_id>/", views.contract_detail, name="contract_detail"),
    path("create_review/<int:booking_id>/", views.create_review, name="create_review"),
    path("contracts/<int:booking_id>/approve/", views.approve_contract, name="approve_contract"),
    path("contracts/<int:booking_id>/decline/", views.decline_contract, name="decline_contract"),
    ]